### ISSUE TITLE
How use bundle?

### ISSUE THREAD

**Issue by allfreelancers** [ekapusta/doctrine-custom-types-bundle#1]
Whare add 
```
use Ekapusta\DoctrineCustomTypesBundle\DBAL\Types;
```
?

**Comment by garex** [comment]
I dont' understand you.

**Comment by allfreelancers** [comment]
How to use a bundle?

**Comment by garex** [comment]
Google this: "How to use symfony bundle".

**Comment by allfreelancers** [comment]
You do not understand, I can not figure out where to add
```
Use Ekapusta \ DoctrineCustomTypesBundle \ DBAL \ Types;
```

**Comment by garex** [comment]
Do you an experienced PHP programmer? Have you worked with symfony and doctrine before?

I dont' know where to add those `use` and why do you want it.

**Comment by allfreelancers** [comment]
How to register this type?

**Comment by garex** [comment]
№2:

> Google this: "How to use symfony bundle".

It's a bundle -- it will do all the stuff when you will use it.

**Comment by allfreelancers** [comment]
Need I add to 
```
doctrine:
    dbal:
        types: 
```
?

**Comment by garex** [comment]
What is it? Where do you get it?

Have you tried to enable bundle and check if it works?

**Comment by allfreelancers** [comment]
Let's in russian: how to add it to  AppKernel ?

```
Add it to Ekapusta\DoctrineCustomTypesBundle\DBAL\Types
Register it at Ekapusta\DoctrineCustomTypesBundle\DBAL\TypeRegistry
```

in which place to add it?

**Comment by garex** [comment]
No. let's stick to english. Good programmer should think in english ))

I think I got your issue.

You dont' need to do those stuff. This is for customizing and extending this bundle.

To use existing types in this bundle you just need to add this symfony bundle to your kernel and this is all you need.

**Comment by allfreelancers** [comment]
Ok.  I have some as
```
new Ekapusta\DoctrineCustomTypesBundle\EkapustaDoctrineCustomTypesBundle(),
```
and
```
    /**
     * Статус
     * @ORM\Column(name="status", nullable=false, type="enum", options={
     *     "values": {"draft"},
     *     "default": "draft"
     * })
     */
    private $status;
```
and error "Could not load type "enum""

**Comment by garex** [comment]
Where do you have those "new bundle()"? In your kernel?

May be you need to clear the cache?

**Comment by allfreelancers** [comment]
In
```
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
```
php bin/console cache:clear --no-warmup
and I have error

**Comment by garex** [comment]
Do you use MySQL?

See https://github.com/ekapusta/doctrine-custom-types-bundle/blob/fa872a5bcb2f8a98d8f003750a13ad47350451fb/DBAL/TypeRegistry.php#L17

Try to debug there — does it actually registered? May be those condition is not solid enough.

**Comment by allfreelancers** [comment]
In config.yml i have 
```
doctrine:
    dbal:
        driver:   pdo_mysql
```
Try to debug there 
how?

**Comment by garex** [comment]
try `var_dump($wtf); exit;`

**Comment by allfreelancers** [comment]
whare is it try?

**Comment by garex** [comment]
> See https://github.com/ekapusta/doctrine-custom-types-bundle/blob/fa872a5bcb2f8a98d8f003750a13ad47350451fb/DBAL/TypeRegistry.php#L17

There.
